services:
  - type: web
    name: sistema-inventario
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /api/sesion
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:sistema_inventario
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
